/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Landing: typeof import('./src/components/Landing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortableContainer: typeof import('./src/components/SortableContainer.vue')['default']
    SortableStackTable: typeof import('./src/components/SortableStackTable.vue')['default']
    Stack: typeof import('./src/components/Stack.vue')['default']
    StackContent: typeof import('./src/components/StackContent.vue')['default']
    StackUpdateTable: typeof import('./src/components/StackUpdateTable.vue')['default']
    UpdateQuelelel: typeof import('./src/components/UpdateQuelelel.vue')['default']
    WashingMachine: typeof import('./src/components/WashingMachine.vue')['default']
  }
}
