services:
  washbackend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.backend
    env_file:
      - .env
    working_dir: /app/data
    networks:
      - washboard-network

  washfrontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.frontend
    depends_on:
      - washbackend
    ports:
      - "10004:80"
    networks:
      - washboard-network

networks:
  washboard-network:
    driver: bridge
