name: Build and Tag Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build backend image
        run: |
          docker build -t washboard-backend:latest -f deploy/Dockerfile.backend .

      - name: Build frontend image
        run: |
          docker build -t washboard-frontend:latest -f deploy/Dockerfile.frontend .

      - name: Push backend image to Docker Hub
        run: |
          docker tag washboard-backend:latest ${{ secrets.DOCKER_USERNAME }}/washboard-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/washboard-backend:latest

      - name: Push frontend image to Docker Hub
        run: |
          docker tag washboard-frontend:latest ${{ secrets.DOCKER_USERNAME }}/washboard-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/washboard-frontend:latest
