name: Build Washboard

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        run: |
          docker build -t ghcr.io/${{ github.repository }}/washboard-backend:latest -f deploy/Dockerfile.backend .
          docker push ghcr.io/${{ github.repository }}/washboard-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t ghcr.io/${{ github.repository }}/washboard-frontend:latest -f deploy/Dockerfile.frontend .
          docker push ghcr.io/${{ github.repository }}/washboard-frontend:latest
